respond to PING sent from client
ThePhilgrim/MantaTail pull request #129
Opened 2022-02-16 17:09 UTC by Akuli

On libera:

```
PING
:strontium.libera.chat 461 akuli-testing PING :Not enough parameters
PING :blah blah
:strontium.libera.chat PONG strontium.libera.chat :blah blah
```

2022-02-16 19:19 UTC, ThePhilgrim requested changes

2022-02-16 19:19 UTC, ThePhilgrim commented on commands.py
> +    """Handles a PING message sent from a client to the server."""
Can we explain in the docstring why the PONG response looks like it does? (Have a look at the docstring of `handle_pong()`

2022-02-16 19:19 UTC, ThePhilgrim commented on commands.py
> +        user.send_que.put(("PONG mantatail :" + args[0], "mantatail"))
I use f-strings throughout the whole code. Would you mind making this an f-string, just for consistency and my mental sanity?

2022-02-16 19:36 UTC, Akuli commented on commands.py
> +    """Handles a PING message sent from a client to the server."""
```suggestion
    """Handles a PING message sent from a client to the server.

    Ex:
    PING :blah blah
    :mantatail PONG mantatail :blah blah
    """
```

2022-02-16 19:36 UTC, Akuli commented on commands.py
> +        user.send_que.put(("PONG mantatail :" + args[0], "mantatail"))
```suggestion
        user.send_que.put((f"PONG mantatail :{args[0]}", "mantatail"))
```

2022-02-16 19:37 UTC, Akuli commented on commands.py
> +    :mantatail PONG mantatail :blah blah
```suggestion
    Ex.
        PING :This_is_a_parameter
        :mantatail PONG mantatail :This_is_a_parameter
```

2022-02-16 19:37 UTC, Akuli commented on commands.py
> +    """Handles a PING message sent from a client to the server.
```suggestion
    """
    Handles a PING message sent from a client to the server.
```

2022-02-16 19:44 UTC, Akuli commented
I think this is ready for another round of reviewing.

2022-02-20 11:33 UTC, ThePhilgrim commented
@Akuli I haven't been on the computer for a few days. Will check this and the mantaray PR tonight!

2022-02-20 19:20 UTC, ThePhilgrim approved these changes

2022-02-20 19:20 UTC, merged